Fix a bug in pipeline to not rebuild jrtc

diff --git a/pipeline/standard-tests.yaml b/pipeline/standard-tests.yaml
--- a/pipeline/standard-tests.yaml
+++ b/pipeline/standard-tests.yaml
@@ -9,12 +9,6 @@ parameters:
 
 steps:
   - bash: |
-      docker tag $(containerRegistry)/jrtc-${{ parameters.dockerType }}:$(imageTag) jrtc
-    displayName: Prepare images
-    failOnStderr: true
-    continueOnError: false
-
-  - bash: |
       echo ${{ parameters.testCase.description }}
       echo sanitizerBuildParam: ${{ parameters.testCase.sanitizerBuildParam }}
     displayName: Display build parameters
@@ -22,7 +16,7 @@ steps:
     continueOnError: false
 
   - bash: |
-      if ! docker run --init --privileged --ulimit memlock=-1 --network host --cap-add=SYS_ADMIN --shm-size=1g --mount type=tmpfs,destination=/dev/shm -e VERBOSE=1 -e JRTC_PATH=/jrtc -e RUN_TESTS=1 -v `pwd`:/jrtc_out_lib -v `pwd`/sample_apps:/jrtc/sample_apps -v `pwd`/jbpf-protobuf/out:/jrtc/jbpf-protobuf/out -v `pwd`/jbpf-protobuf/jbpf/out:/jrtc/jbpf-protobuf/jbpf/out ${{parameters.testCase['sanitizerBuildParam']}} jrtc; then
+      if ! docker run --init --privileged --ulimit memlock=-1 --network host --cap-add=SYS_ADMIN --shm-size=1g --mount type=tmpfs,destination=/dev/shm -e VERBOSE=1 -e JRTC_PATH=/jrtc -e RUN_TESTS=1 -v `pwd`:/jrtc_out_lib -v `pwd`/sample_apps:/jrtc/sample_apps -v `pwd`/jbpf-protobuf/out:/jrtc/jbpf-protobuf/out -v `pwd`/jbpf-protobuf/jbpf/out:/jrtc/jbpf-protobuf/jbpf/out ${{parameters.testCase['sanitizerBuildParam']}} $(containerRegistry)/jrtc-${{ parameters.dockerType }}:$(imageTag) jrtc; then
         echo Error code is $?
         exit 1
       fi
@@ -49,13 +43,14 @@ steps:
           -e VERBOSE=1 \
           -e JRTC_PATH=/jrtc \
           -v `pwd`:/jrtc_out_lib \
+          -v `pwd/out:/jrtc/out \
           -v `pwd`/sample_apps:/jrtc/sample_apps \
           -v `pwd`/jbpf-protobuf/out:/jrtc/jbpf-protobuf/out \
           -v `pwd`/jbpf-protobuf/jbpf/out:/jrtc/jbpf-protobuf/jbpf/out \
           ${{parameters.testCase['sanitizerBuildParam']}} \
           --entrypoint=/jrtc/helper_build_files/integration_tests.sh \
-          jrtc \
-          $TEST |& tee /tmp/output.log; then
+          $(containerRegistry)/jrtc-${{ parameters.dockerType }}:$(imageTag) \
+          ${TEST} |& tee /tmp/output.log; then
             echo "Error Running JRTC Tests for $TEST"
           exit 1
         fi
@@ -66,26 +61,36 @@ steps:
         ## Copy to artifacts
         cp /tmp/output.log $(Build.ArtifactStagingDirectory)/output_${{ parameters.testCase.id }}_${{ parameters.dockerType }}_${TEST}.log
         
-        count=$(grep "Aggregate counter so far is" /tmp/output.log | wc -l)
-        echo "The result count for $TEST is $count"
-        
-        if [[ $count -eq 0 ]]; then
-          echo ".......................................................................................... Test $TEST failed..........................................................................................."
+        if ! docker run --init --privileged \
+          --ulimit memlock=-1 \
+          --network host \
+          --cap-add=SYS_ADMIN \
+          --shm-size=1g \
+          --mount type=tmpfs,destination=/dev/shm \
+          -e VERBOSE=1 \
+          -e JRTC_PATH=/jrtc \
+          -v `pwd`:/jrtc_out_lib \
+          -v /tmp/output.log:/tmp/output.log \
+          -v `pwd`/sample_apps:/jrtc/sample_apps \
+          -v `pwd`/jbpf-protobuf/out:/jrtc/jbpf-protobuf/out \
+          -v `pwd`/jbpf-protobuf/jbpf/out:/jrtc/jbpf-protobuf/jbpf/out \
+          ${{parameters.testCase['sanitizerBuildParam']}} \
+          --entrypoint=/jrtc/sample_apps/$TEST/assert.sh \
+          $(containerRegistry)/jrtc-${{ parameters.dockerType }}:$(imageTag) \
+          /tmp/output.log; then
+            echo "Test Assertion failed for $TEST"
           exit 1
         else
-          echo "..........................................................................................Test $TEST passed..........................................................................................."
+          echo "Test Assertion passed for $TEST"
         fi
       done
     
     displayName: Integration Tests sample apps
     continueOnError: false
 
-  - task: PublishTestResults@2
+  # Publish logs as artifacts
+  - task: PublishBuildArtifacts@1
+    displayName: "Publish Logs"
     inputs:
-      testResultsFormat: "JUnit" # Options: JUnit, NUnit, VSTest, xUnit, cTest
-      testResultsFiles: "**/**/*.tests.xml"
-      #searchFolder: '$(System.DefaultWorkingDirectory)' # Opastional
-      mergeTestResults: true # Optional
-      failTaskOnFailedTests: true
-    continueOnError: false
-
+      pathToPublish: "$(Build.ArtifactStagingDirectory)"
+      artifactName: "TestLogs"
